# Generated by Django 5.1.4 on 2026-05-14 05:08

import apps.core.crypto
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_expand_currency_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='gemini_api_key',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='business',
            name='groq_api_key',
            field=apps.core.crypto.EncryptedCharField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='business',
            name='llm_provider',
            field=models.CharField(choices=[('anthropic', 'Anthropic Claude'), ('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini'), ('groq', 'Groq (free)')], default='anthropic', help_text='Which LLM powers Anna and lead extraction.', max_length=16),
        ),
    ]
