import type { Lang } from "./langs";
import { en as enFromShared, type Dict as SharedDict } from "./strings-en";

type Dict = SharedDict;

export const en: Dict = enFromShared;

const es: Dict = {
  "nav.features": "Funciones",
  "nav.how": "Cómo funciona",
  "nav.impact": "Impacto",
  "nav.industries": "Sectores",
  "nav.docs": "Documentación",
  "btn.signIn": "Iniciar sesión",
  "btn.bookDemo": "Reservar demo",
  "btn.explore": "Explorar",
  "btn.tellUs": "Cuéntanos el tuyo",
  "topbar.builtBy": "por",

  "hero.meetStrong": "Hola, soy Anna.",
  "hero.meetTail": " Esta noche atiendo el teléfono — vete a dormir.",
  "hero.tradesLabel": "Hecho para servicios del hogar —",
  "hero.tradesList": "HVAC · Fontanería · Tejados · Solar · Garaje · Eléctrico · Jardinería · Limpieza · Plagas",
  "hero.title1": "Son las 23:47. Tu teléfono está sonando.",
  "hero.title2": "No te preocupes.",
  "hero.sub": "Anna contesta, califica, presupuesta y reserva — para que tu equipo duerma y tu agenda se llene sola.",
  "hero.oss": "Código abierto · AGPL-3.0",
  "hero.star": "★ Dale estrella en GitHub",
  "hero.selfHost": "Auto-aloja o instalación llave en mano",

  "story.eyebrow": "Cómo se siente",
  "story.title1": "Una llamada perdida,",
  "story.title2": "convertida en trabajo reservado.",
  "story.sub": "Recorre una noche, como Anna realmente la gestiona.",
  "story.s1.beat": "Es tarde. Suena el teléfono.",
  "story.s1.body": "23:47. Tu equipo duerme. La competencia también. El cliente tiene 30 segundos de paciencia.",
  "story.s2.beat": "Anna contesta.",
  "story.s2.body": "Saluda al cliente con la voz de tu negocio, hace las preguntas correctas y descubre que es un trabajo de 5 ventanas en el salón.",
  "story.s3.beat": "Foto. Presupuesto. Confirmado.",
  "story.s3.body": "El cliente envía una foto. Anna mide desde la imagen, redacta un presupuesto de $3.540 y ofrece una visita el martes a las 9:30 — todo antes de irse a la cama.",
  "story.s4.beat": "Despiertas con la agenda llena.",
  "story.s4.body": "Café de la mañana. Una visita en el calendario, un presupuesto enviado, un depósito esperando. No has tocado el teléfono.",
  "story.s4.foot": "Todo de noche. Nadie estaba despierto.",

  "features.eyebrow": "Funciones",
  "features.title": "Configúralo una vez. Captura cada lead.",
  "features.sub": "Define tu horario, reglas de precios y zona de servicio. Hearthline se adapta a tu oficio — desde una urgencia de fontanería a las 2 AM hasta un presupuesto solar de $25.000 al mediodía.",
  "features.f1.name": "Recepcionista IA por teléfono",
  "features.f1.body": "Nunca pierdas otra llamada. Hearthline contesta antes del segundo tono, califica al cliente en tiempo real y reserva la cita directamente en el calendario de tu equipo — con la voz que elijas y el guion de tu negocio.",
  "features.f2.name": "Asistente de chat IA",
  "features.f2.body": "Chat web, SMS y WhatsApp — la misma Anna, la misma memoria del cliente. Responde en segundos y solo deriva a un humano cuando es necesario.",
  "features.f3.name": "Integración con CRM",
  "features.f3.body": "Cada llamada, mensaje y presupuesto entra en tu CRM como un registro limpio — HubSpot, Pipedrive, Jobber, ServiceTitan o tu propio Postgres.",
  "features.f4.name": "Presupuestos inteligentes",
  "features.f4.body": "El cliente envía una foto. Anna mide con visión, redacta partidas, aplica tus reglas de IVA y margen, y envía un presupuesto listo para Stripe.",
  "features.f5.name": "Base de conocimiento IA",
  "features.f5.body": "Sube tu garantía, catálogo de servicios y FAQ. Anna cita tus condiciones reales — nunca inventa un precio ni una promesa que no haces.",
  "features.f6.name": "Análisis de datos",
  "features.f6.body": "Paneles en directo de volumen de llamadas, calidad de leads, conversión e ingresos por canal — para demostrar que el turno de noche se paga solo.",

  "stats.eyebrow": "Por qué cambian",
  "stats.title": "Cada llamada perdida es un trabajo que reserva tu competencia.",
  "stats.body": "Hearthline atiende cada entrada en cada canal, la califica al instante y entrega a tu equipo una conversación lista para cerrar. Anna no duerme, no hace pausas y nunca olvida pedir la foto.",
  "stats.li1": "Llamadas atendidas mientras estás en un tejado a las 3 AM",
  "stats.li2": "Fotos convertidas en presupuestos antes de terminar tu café",
  "stats.li3": "Cada interacción sincronizada con HubSpot, Pipedrive o tu CRM",
  "stats.card1.num": "3 AM",
  "stats.card1.label": "La urgencia de tubería rota que tu competidor perdió. Anna la atendió.",
  "stats.card2.num": "43 s",
  "stats.card2.label": "Tiempo medio entre la foto del cliente y el PDF de presupuesto.",
  "stats.card3.num": "$0",
  "stats.card3.label": "Por llamada perdida. Hearthline reserva las que tu bandeja pierde.",

  "flow.eyebrow": "Cómo fluye",
  "flow.title": "Cómo fluye un trabajo por Hearthline.",
  "flow.sub": "Cinco etapas, totalmente automatizadas. El cliente no nota los traspasos — sólo recibe respuesta rápida, presupuesto y cita reservada.",

  "convo.eyebrow": "Una conversación real",
  "convo.title": "Anna gestiona la objeción, no sólo el saludo.",
  "convo.sub": "Hilo SMS en directo entre Anna y un cliente. Llega la foto, se redacta el presupuesto, se crea el deal, se reserva la cita — todo automático.",
  "convo.head.title": "Automatización de leads entrantes",
  "convo.head.sub": "Califica el lead, sincroniza el CRM, redacta un presupuesto — automáticamente.",
  "convo.msg1": "Necesito sustituir unas 5 ventanas en el salón. Busco PVC blanco.",
  "convo.msg2": "Entendido — 5 ventanas de PVC, blancas. ¿Doble acristalamiento estándar, o triple por ruido / energía? ¿Puedes hacer una foto rápida de una ventana desde dentro?",
  "convo.msg3": "Doble acristalamiento está bien. Aquí va la foto.",
  "convo.msg4Pre": "Perfecto — medidas ~120×140 cm desde tu foto. Cinco unidades, suministro e instalación: ",
  "convo.msg4Mid": " IVA incluido. Te he enviado el desglose y una visita de medición el martes a las 9:30. Toca el enlace para confirmar.",
  "convo.output": "Resultado",
  "convo.estimate": "Presupuesto #E-291 · enviado",
  "convo.deal": "Deal creado · HubSpot",
  "convo.survey": "Visita reservada · Mar 9:30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "Oficios",
  "industries.title": "Una plataforma. Todos los oficios.",
  "industries.sub": "La lógica de precios, los guiones y las reglas de despacho vienen pre-ajustados para cada oficio — y son totalmente editables. ¿No ves el tuyo? Hearthline se configura para cualquier flujo del hogar.",
  "industries.note": "Además: ¿no está en la lista? Hearthline encaja con el flujo que ya usa tu equipo. ",
  "industries.i1.name": "HVAC y Fontanería",
  "industries.i1.body": "Enrutado de urgencias 24/7, despacho de técnicos, contratos de mantenimiento.",
  "industries.i2.name": "Ventanas y Puertas",
  "industries.i2.body": "Presupuestos por foto, citas de medición, reservas de instalación.",
  "industries.i3.name": "Solar y Tejados",
  "industries.i3.body": "Cualificación del tejado, búsqueda de subvenciones, coordinación de visitas.",
  "industries.i4.name": "Renovación energética",
  "industries.i4.body": "Auditorías de aislamiento, ayudas, flujos de reforma multi-etapa.",
  "industries.i5.name": "Garajes y Persianas",
  "industries.i5.body": "Identificación de marca y modelo, reparar vs reemplazar, llamadas fuera de horario.",
  "industries.i6.name": "Electricidad",
  "industries.i6.body": "Triaje urgencia vs programado, guiones de seguridad, upsell de domótica.",
  "industries.i7.name": "Jardinería y Piscinas",
  "industries.i7.body": "Calendario estacional, contratos recurrentes, presupuestos por foto.",
  "industries.i8.name": "Limpieza y Restauración",
  "industries.i8.body": "Triaje de daños, enrutado a seguros, reserva recurrente, fotos antes/después.",
  "industries.i9.name": "Control de plagas",
  "industries.i9.body": "Triaje de síntomas, contratos recurrentes, upsell de cobertura vecinal, seguimientos.",

  "config.eyebrow": "Configurable de extremo a extremo",
  "config.title": "Tu voz. Tus precios. Tu CRM. Tu horario.",
  "config.body": "Elige entre más de 30 voces neuronales en 7 idiomas. Carga tu tarifa. Conecta HubSpot, Pipedrive, Salesforce, ServiceTitan o tu API. Define horarios por canal. Hearthline se adapta a tus reglas — no al revés.",
  "config.k1.l": "Voz",
  "config.k1.v": "30+ neuronales · 7 idiomas",
  "config.k2.l": "Precios",
  "config.k2.v": "Tu tarifa · reglas por oficio",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Horario",
  "config.k4.v": "Por canal · por día · festivos",
  "config.k5.l": "Clonación de voz",
  "config.k5.v": "Usa la voz del dueño (opcional)",
  "config.k6.l": "Auto-alojado",
  "config.k6.v": "Código AGPL-3.0 en GitHub (licencia comercial disponible)",

  "finalCta.title": "Mantén el fuego encendido. Nosotros vigilamos la puerta.",
  "finalCta.sub": "Anna atiende la urgencia de las 3 AM, la llamada del descanso y la foto del cliente que no sabe describir la fuga. Tu equipo sigue en el trabajo — la agenda se llena sola.",

  "footer.tag": "El centro de comunicación IA 24/7 para servicios del hogar.",
  "footer.product": "Producto",
  "footer.resources": "Recursos",
  "footer.legal": "Legal",
  "footer.faq": "Preguntas",
  "footer.privacy": "Privacidad",
  "footer.terms": "Términos",
  "footer.builtBy": "Hecho por",
  "footer.bio": "Vídeos de construcción IA para devs que envían agentes reales. Contrátame para desplegar Hearthline en tu negocio.",
  "footer.copyright": "Código abierto bajo AGPL-3.0. Licencia comercial disponible.",
  "footer.bottomTail": "con cariño para equipos del hogar.",

  "lang.label": "Idioma",
};

const de: Dict = {
  "nav.features": "Funktionen",
  "nav.how": "So funktioniert's",
  "nav.impact": "Wirkung",
  "nav.industries": "Branchen",
  "nav.docs": "Dokumentation",
  "btn.signIn": "Anmelden",
  "btn.bookDemo": "Demo buchen",
  "btn.explore": "Entdecken",
  "btn.tellUs": "Erzählen Sie uns von Ihrem",
  "topbar.builtBy": "von",

  "hero.meetStrong": "Hi, ich bin Anna.",
  "hero.meetTail": " Heute Nacht bin ich am Telefon — geh ins Bett.",
  "hero.tradesLabel": "Gebaut für Handwerk —",
  "hero.tradesList": "HLK · Sanitär · Dach · Solar · Garage · Elektrik · Garten · Reinigung · Schädlinge",
  "hero.title1": "Es ist 23:47 Uhr. Dein Telefon klingelt.",
  "hero.title2": "Mach dir keine Sorgen.",
  "hero.sub": "Anna nimmt ab, qualifiziert, kalkuliert und bucht — damit dein Team schläft und dein Kalender sich von selbst füllt.",
  "hero.oss": "Open Source · AGPL-3.0",
  "hero.star": "★ Auf GitHub markieren",
  "hero.selfHost": "Selbst hosten oder Komplett-Setup",

  "story.eyebrow": "So fühlt es sich an",
  "story.title1": "Ein verpasster Anruf,",
  "story.title2": "wird zum gebuchten Auftrag.",
  "story.sub": "Eine Nacht, wie Anna sie wirklich abwickelt.",
  "story.s1.beat": "Es ist spät. Das Telefon klingelt.",
  "story.s1.body": "23:47 Uhr. Dein Team schläft. Die Konkurrenz auch. Der Kunde hat 30 Sekunden Geduld.",
  "story.s2.beat": "Anna nimmt ab.",
  "story.s2.body": "Sie begrüßt den Anrufer mit der Stimme deines Betriebs, stellt die richtigen Fragen und erfährt, dass es um 5 Fenster im Wohnzimmer geht.",
  "story.s3.beat": "Foto. Angebot. Bestätigt.",
  "story.s3.body": "Der Kunde sendet ein Foto. Anna misst aus dem Bild, erstellt ein Angebot über 3.540 € und schlägt einen Termin am Dienstag um 9:30 vor — alles vor dem Schlafengehen.",
  "story.s4.beat": "Du wachst gebucht auf.",
  "story.s4.body": "Morgenkaffee. Ein Termin im Kalender, ein versendetes Angebot, eine wartende Anzahlung. Du hast das Telefon nicht angefasst.",
  "story.s4.foot": "Alles über Nacht. Niemand war wach.",

  "features.eyebrow": "Funktionen",
  "features.title": "Einmal einrichten. Jeden Lead erfassen.",
  "features.sub": "Geschäftszeiten, Preisregeln und Servicegebiet festlegen. Hearthline passt sich Ihrem Gewerk an — vom Notdienst-Klempner um 2 Uhr bis zum 25.000 € Solar-Angebot mittags.",
  "features.f1.name": "KI-Telefon-Rezeption",
  "features.f1.body": "Verpassen Sie keinen Anruf mehr. Hearthline nimmt jeden Anruf binnen zwei Klingeltönen an, qualifiziert in Echtzeit und bucht den Termin direkt im Kalender Ihres Teams — mit Wunschstimme und Ihrem Skript.",
  "features.f2.name": "KI-Chat-Assistent",
  "features.f2.body": "Web-Chat, SMS und WhatsApp — dieselbe Anna, dieselbe Kundenhistorie. Antwortet in Sekunden, gibt nur an Menschen ab, wenn es sein muss.",
  "features.f3.name": "CRM-Integration",
  "features.f3.body": "Jeder Anruf, jede Nachricht und jedes Angebot landet als sauberer Datensatz im CRM — HubSpot, Pipedrive, Jobber, ServiceTitan oder dein eigenes Postgres.",
  "features.f4.name": "Smartes Angebot",
  "features.f4.body": "Kunden senden ein Foto. Anna misst per Vision, erstellt Positionen, wendet Steuer- und Margenregeln an und sendet ein Stripe-fähiges Angebot.",
  "features.f5.name": "KI-Wissensbasis",
  "features.f5.body": "Lade Garantietext, Leistungskatalog und FAQ hoch. Anna nennt deine echten Konditionen — erfindet nie einen Preis oder ein Versprechen.",
  "features.f6.name": "Datenanalyse",
  "features.f6.body": "Live-Dashboards zu Anrufvolumen, Lead-Qualität, Conversion und Umsatz pro Kanal — damit du beweist, dass die Nachtschicht sich rechnet.",

  "stats.eyebrow": "Warum Teams wechseln",
  "stats.title": "Jeder verpasste Anruf ist ein Auftrag für die Konkurrenz.",
  "stats.body": "Hearthline nimmt jeden Eingang über jeden Kanal an, qualifiziert sofort und übergibt eine abschlussreife Konversation. Anna schläft nie, macht keine Pausen und vergisst nie, das Foto anzufordern.",
  "stats.li1": "Anrufe um 3 Uhr morgens, während Sie auf dem Dach sind",
  "stats.li2": "Fotos werden zu Angeboten, bevor der Kaffee kalt ist",
  "stats.li3": "Jede Interaktion synchronisiert mit HubSpot, Pipedrive oder Ihrem CRM",
  "stats.card1.num": "3 Uhr",
  "stats.card1.label": "Der Rohrbruch-Notruf, den die Konkurrenz verpasst hat. Anna war dran.",
  "stats.card2.num": "43 Sek",
  "stats.card2.label": "Durchschnitt vom Kundenfoto bis zum fertigen PDF-Angebot.",
  "stats.card3.num": "0 €",
  "stats.card3.label": "Pro verpasstem Anruf. Hearthline bucht das, was Ihr Posteingang verliert.",

  "flow.eyebrow": "Der Ablauf",
  "flow.title": "Wie ein Auftrag durch Hearthline läuft.",
  "flow.sub": "Fünf Schritte, voll automatisiert. Der Kunde merkt nichts von den Übergaben — er bekommt nur schnelle Antwort, Angebot und festen Termin.",

  "convo.eyebrow": "Ein echtes Gespräch",
  "convo.title": "Anna behandelt den Einwand, nicht nur das Hallo.",
  "convo.sub": "Live-SMS-Dialog zwischen Anna und Kunde. Foto kommt, Angebot wird erstellt, Deal angelegt, Termin gebucht — alles automatisch.",
  "convo.head.title": "Eingehende Lead-Automatisierung",
  "convo.head.sub": "Qualifiziert den Lead, synct ins CRM, erstellt ein Angebot — automatisch.",
  "convo.msg1": "Ich muss etwa 5 Fenster im Wohnzimmer ersetzen. Suche weißes PVC.",
  "convo.msg2": "Verstanden — 5 PVC-Fenster, weiß. Standard-Doppelverglasung oder Dreifach für Schall / Energie? Können Sie ein schnelles Foto eines Fensters von innen machen?",
  "convo.msg3": "Doppelverglasung passt. Hier ist ein Foto.",
  "convo.msg4Pre": "Perfekt — vermessen ~120×140 cm vom Foto. Fünf Stück, Lieferung und Einbau: ",
  "convo.msg4Mid": " inkl. MwSt. Ich habe Ihnen die Aufschlüsselung und einen Aufmaß-Termin am Dienstag 9:30 Uhr per SMS geschickt.",
  "convo.output": "Ergebnis",
  "convo.estimate": "Angebot #E-291 · gesendet",
  "convo.deal": "Deal erstellt · HubSpot",
  "convo.survey": "Aufmaß gebucht · Di 9:30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "Gewerke",
  "industries.title": "Eine Plattform. Jedes Gewerk.",
  "industries.sub": "Preislogik, Skripte und Dispositionsregeln sind pro Gewerk vor-eingestellt — und voll editierbar. Nicht dabei? Hearthline lässt sich auf jeden Handwerks-Workflow konfigurieren.",
  "industries.note": "Plus: nicht in der Liste? Hearthline passt in jeden Ablauf, den Ihr Team schon nutzt. ",
  "industries.i1.name": "Heizung & Sanitär",
  "industries.i1.body": "Notdienst-Routing 24/7, Technikerdisposition, Wartungsverträge.",
  "industries.i2.name": "Fenster & Türen",
  "industries.i2.body": "Foto-Angebote, Aufmaß-Termine, Montagebuchungen.",
  "industries.i3.name": "Solar & Dach",
  "industries.i3.body": "Dachprüfung, Förderabgleich, Vor-Ort-Termine.",
  "industries.i4.name": "Energetische Sanierung",
  "industries.i4.body": "Dämm-Audits, Förderanträge, mehrstufige Sanierungs-Flows.",
  "industries.i5.name": "Garage & Rollläden",
  "industries.i5.body": "Marken-/Modellerkennung, Reparieren vs Ersetzen, Anrufe nach Feierabend.",
  "industries.i6.name": "Elektro",
  "industries.i6.body": "Notfall- vs Plan-Triage, Sicherheitsskripte, Smart-Home-Upsell.",
  "industries.i7.name": "Garten & Pool",
  "industries.i7.body": "Saisonale Planung, Jahresverträge, Foto-Schätzungen.",
  "industries.i8.name": "Reinigung & Sanierung",
  "industries.i8.body": "Schaden-Triage, Versicherungs-Routing, wiederkehrende Buchungen, Vorher/Nachher.",
  "industries.i9.name": "Schädlingsbekämpfung",
  "industries.i9.body": "Symptom-Triage, Verträge, Nachbar-Upsell, Nachfassen.",

  "config.eyebrow": "Voll konfigurierbar",
  "config.title": "Ihre Stimme. Ihre Preise. Ihr CRM. Ihre Zeiten.",
  "config.body": "Wählen Sie aus 30+ neuronalen Stimmen in 7 Sprachen. Eigene Preisliste hochladen. HubSpot, Pipedrive, Salesforce, ServiceTitan oder eigene API anbinden. Geschäftszeiten je Kanal. Hearthline läuft nach Ihren Regeln — nicht umgekehrt.",
  "config.k1.l": "Stimme",
  "config.k1.v": "30+ neuronal · 7 Sprachen",
  "config.k2.l": "Preise",
  "config.k2.v": "Eigene Liste · pro Gewerk",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Zeiten",
  "config.k4.v": "Pro Kanal · pro Tag · Feiertage",
  "config.k5.l": "Stimm-Klon",
  "config.k5.v": "Stimme des Inhabers (optional)",
  "config.k6.l": "Self-Host",
  "config.k6.v": "AGPL-3.0-Code auf GitHub (kommerzielle Lizenz verfügbar)",

  "finalCta.title": "Halten Sie das Feuer am Brennen. Wir bewachen die Tür.",
  "finalCta.sub": "Anna nimmt den 3-Uhr-Notruf, den Mittagspausen-Rückruf und das Foto vom Kunden, der das Leck nicht in Worte fassen kann. Ihr Team bleibt am Werkzeug — der Kalender füllt sich selbst.",

  "footer.tag": "Der 24/7 KI-Kommunikations-Hub für Handwerksbetriebe.",
  "footer.product": "Produkt",
  "footer.resources": "Ressourcen",
  "footer.legal": "Rechtliches",
  "footer.faq": "FAQ",
  "footer.privacy": "Datenschutz",
  "footer.terms": "AGB",
  "footer.builtBy": "Gebaut von",
  "footer.bio": "KI-Build-Along-Videos für Entwickler. Buchen Sie mich für die Hearthline-Einrichtung.",
  "footer.copyright": "Open Source unter AGPL-3.0. Kommerzielle Lizenz verfügbar.",
  "footer.bottomTail": "mit Sorgfalt für Handwerksbetriebe.",

  "lang.label": "Sprache",
};

const fr: Dict = {
  "nav.features": "Fonctionnalités",
  "nav.how": "Comment ça marche",
  "nav.impact": "Impact",
  "nav.industries": "Métiers",
  "nav.docs": "Docs",
  "btn.signIn": "Connexion",
  "btn.bookDemo": "Réserver une démo",
  "btn.explore": "Explorer",
  "btn.tellUs": "Parlez-nous du vôtre",
  "topbar.builtBy": "par",

  "hero.meetStrong": "Salut, je suis Anna.",
  "hero.meetTail": " Je m'occupe du téléphone ce soir — va te coucher.",
  "hero.tradesLabel": "Conçu pour les services à domicile —",
  "hero.tradesList": "CVC · Plomberie · Toiture · Solaire · Garage · Électrique · Paysage · Nettoyage · Nuisibles",
  "hero.title1": "Il est 23h47. Ton téléphone sonne.",
  "hero.title2": "Ne t'en fais pas.",
  "hero.sub": "Anna répond, qualifie, devise et réserve — pour que ton équipe dorme et que ton agenda se remplisse tout seul.",
  "hero.oss": "Open source · AGPL-3.0",
  "hero.star": "★ Étoile sur GitHub",
  "hero.selfHost": "Auto-hébergement ou installation clé en main",

  "story.eyebrow": "Ce que ça donne",
  "story.title1": "Un appel manqué,",
  "story.title2": "transformé en travail réservé.",
  "story.sub": "Vis une nuit comme Anna la gère vraiment.",
  "story.s1.beat": "Il est tard. Le téléphone sonne.",
  "story.s1.body": "23h47. Ton équipe dort. La concurrence aussi. Le client a 30 secondes de patience.",
  "story.s2.beat": "Anna décroche.",
  "story.s2.body": "Elle accueille l'appelant avec la voix de ton entreprise, pose les bonnes questions et découvre qu'il s'agit de 5 fenêtres dans le salon.",
  "story.s3.beat": "Photo. Devis. Confirmé.",
  "story.s3.body": "Le client envoie une photo. Anna mesure depuis l'image, rédige un devis de 3 540 € et propose un créneau le mardi à 9h30 — avant qu'il aille se coucher.",
  "story.s4.beat": "Tu te réveilles réservé.",
  "story.s4.body": "Café du matin. Une visite au calendrier, un devis envoyé, un acompte en attente. Tu n'as pas touché le téléphone.",
  "story.s4.foot": "Tout dans la nuit. Personne n'était éveillé.",

  "features.eyebrow": "Fonctionnalités",
  "features.title": "Configurez une fois. Captez chaque lead.",
  "features.sub": "Définissez vos horaires, règles tarifaires et zone de service. Hearthline s'adapte à votre métier — de la plomberie d'urgence à 2h à un devis solaire de 25 000 € à midi.",
  "features.f1.name": "Standard téléphonique IA",
  "features.f1.body": "Ne ratez plus un appel. Hearthline décroche en deux sonneries, qualifie le lead en temps réel et réserve directement dans le calendrier de votre équipe — avec la voix de votre choix et votre script.",
  "features.f2.name": "Assistant chat IA",
  "features.f2.body": "Chat web, SMS et WhatsApp — la même Anna, la même mémoire du client. Répond en secondes, ne passe à un humain que quand il le faut.",
  "features.f3.name": "Intégration CRM",
  "features.f3.body": "Chaque appel, message et devis entre dans ton CRM en fiche propre — HubSpot, Pipedrive, Jobber, ServiceTitan ou ton propre Postgres.",
  "features.f4.name": "Devis intelligents",
  "features.f4.body": "Les clients envoient une photo. Anna mesure par vision, rédige les lignes, applique tes règles de TVA et de marge, et envoie un devis prêt pour Stripe.",
  "features.f5.name": "Base de connaissances IA",
  "features.f5.body": "Ajoute ta garantie, ton catalogue de services et ta FAQ. Anna cite tes vraies conditions — n'invente jamais un prix ou une promesse.",
  "features.f6.name": "Analytique",
  "features.f6.body": "Tableaux de bord en direct sur le volume d'appels, la qualité des leads, la conversion et les revenus par canal — pour prouver que la nuit se paie toute seule.",

  "stats.eyebrow": "Pourquoi changer",
  "stats.title": "Chaque appel manqué est un chantier pour le concurrent.",
  "stats.body": "Hearthline répond sur tous les canaux, qualifie immédiatement et livre à votre équipe une conversation prête à signer. Anna ne dort jamais, ne fait pas de pause et n'oublie jamais la photo.",
  "stats.li1": "Appels pris pendant que vous êtes sur un toit à 3h",
  "stats.li2": "Photos transformées en devis avant la fin du café",
  "stats.li3": "Toutes les interactions synchro HubSpot, Pipedrive ou votre CRM",
  "stats.card1.num": "3h",
  "stats.card1.label": "La fuite à 3h que le concurrent a ratée. Anna a répondu.",
  "stats.card2.num": "43 s",
  "stats.card2.label": "Temps moyen entre la photo et le devis PDF.",
  "stats.card3.num": "0 €",
  "stats.card3.label": "Par appel manqué. Hearthline réserve ceux que votre boîte perd.",

  "flow.eyebrow": "Le parcours",
  "flow.title": "Comment un job passe par Hearthline.",
  "flow.sub": "Cinq étapes, automatisées. Le client ne sent pas les transitions — réponse rapide, devis, créneau réservé.",

  "convo.eyebrow": "Une vraie conversation",
  "convo.title": "Anna gère l'objection, pas que le bonjour.",
  "convo.sub": "Fil SMS en direct entre Anna et un client. La photo arrive, le devis est rédigé, le deal créé, le rendez-vous posé — tout automatique.",
  "convo.head.title": "Automatisation des leads entrants",
  "convo.head.sub": "Qualifie le lead, synchronise le CRM, rédige un devis — automatiquement.",
  "convo.msg1": "Je dois remplacer environ 5 fenêtres dans mon salon. Du PVC blanc.",
  "convo.msg2": "Compris — 5 fenêtres PVC blanc. Double vitrage standard, ou triple pour le bruit / l'énergie ? Pouvez-vous prendre une photo rapide d'une fenêtre depuis l'intérieur ?",
  "convo.msg3": "Double vitrage c'est bon. Voici une photo.",
  "convo.msg4Pre": "Parfait — mesures ~120×140 cm sur la photo. Cinq unités, fourniture et pose : ",
  "convo.msg4Mid": " TTC. Je vous ai envoyé le détail et un créneau métré mardi 9h30. Cliquez le lien pour confirmer.",
  "convo.output": "Résultat",
  "convo.estimate": "Devis #E-291 · envoyé",
  "convo.deal": "Deal créé · HubSpot",
  "convo.survey": "Métré réservé · Mar 9h30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "Métiers",
  "industries.title": "Une plateforme. Tous les métiers.",
  "industries.sub": "Logique tarifaire, scripts et règles de dispatch pré-réglés par métier — entièrement modifiables. Le vôtre n'y est pas ? Hearthline se configure pour tout flux du domicile.",
  "industries.note": "Et : pas dans la liste ? Hearthline s'intègre au flux que votre équipe utilise déjà. ",
  "industries.i1.name": "CVC & Plomberie",
  "industries.i1.body": "Routage urgences 24/7, dispatch technicien, contrats d'entretien.",
  "industries.i2.name": "Fenêtres & Portes",
  "industries.i2.body": "Devis sur photo, prise de mesure, réservation pose.",
  "industries.i3.name": "Solaire & Toiture",
  "industries.i3.body": "Qualification de toiture, primes, coordination visite.",
  "industries.i4.name": "Rénovation énergétique",
  "industries.i4.body": "Audits isolation, demandes d'aides, parcours multi-étapes.",
  "industries.i5.name": "Garage & Volets",
  "industries.i5.body": "Identification marque/modèle, réparer ou remplacer, appels hors horaires.",
  "industries.i6.name": "Électricité",
  "industries.i6.body": "Triage urgence/planifié, scripts de sécurité, upsell domotique.",
  "industries.i7.name": "Paysage & Piscines",
  "industries.i7.body": "Calendrier saisonnier, contrats récurrents, devis sur photo.",
  "industries.i8.name": "Nettoyage & Restauration",
  "industries.i8.body": "Triage des dégâts, routage assurance, réservation récurrente, avant/après.",
  "industries.i9.name": "Nuisibles",
  "industries.i9.body": "Triage symptômes, contrats, upsell voisinage, suivis.",

  "config.eyebrow": "Configurable de bout en bout",
  "config.title": "Votre voix. Vos prix. Votre CRM. Vos horaires.",
  "config.body": "Plus de 30 voix neuronales en 7 langues. Importez votre grille tarifaire. Connectez HubSpot, Pipedrive, Salesforce, ServiceTitan ou votre API. Horaires par canal. Hearthline suit vos règles — pas l'inverse.",
  "config.k1.l": "Voix",
  "config.k1.v": "30+ neuronales · 7 langues",
  "config.k2.l": "Tarifs",
  "config.k2.v": "Votre grille · règles par métier",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Horaires",
  "config.k4.v": "Par canal · par jour · jours fériés",
  "config.k5.l": "Clonage de voix",
  "config.k5.v": "Voix du patron (optionnel)",
  "config.k6.l": "Auto-hébergé",
  "config.k6.v": "Code AGPL-3.0 sur GitHub (licence commerciale disponible)",

  "finalCta.title": "Gardez le feu allumé. On surveille la porte.",
  "finalCta.sub": "Anna prend l'urgence de 3h, le rappel du déjeuner et la photo du client qui ne sait pas décrire la fuite. Votre équipe reste sur le terrain — l'agenda se remplit seul.",

  "footer.tag": "Le hub de communication IA 24/7 pour les services à domicile.",
  "footer.product": "Produit",
  "footer.resources": "Ressources",
  "footer.legal": "Mentions",
  "footer.faq": "FAQ",
  "footer.privacy": "Confidentialité",
  "footer.terms": "CGU",
  "footer.builtBy": "Conçu par",
  "footer.bio": "Vidéos build-along IA pour devs. Embauchez-moi pour déployer Hearthline.",
  "footer.copyright": "Open source sous AGPL-3.0. Licence commerciale disponible.",
  "footer.bottomTail": "avec soin pour les équipes du domicile.",

  "lang.label": "Langue",
};

const it: Dict = {
  "nav.features": "Funzioni",
  "nav.how": "Come funziona",
  "nav.impact": "Impatto",
  "nav.industries": "Settori",
  "nav.docs": "Docs",
  "btn.signIn": "Accedi",
  "btn.bookDemo": "Prenota una demo",
  "btn.explore": "Esplora",
  "btn.tellUs": "Raccontaci il tuo",
  "topbar.builtBy": "di",

  "hero.meetStrong": "Ciao, sono Anna.",
  "hero.meetTail": " Stanotte rispondo io al telefono — vai a dormire.",
  "hero.tradesLabel": "Pensato per i servizi alla casa —",
  "hero.tradesList": "Climatizzazione · Idraulica · Tetti · Solare · Garage · Elettrico · Giardinaggio · Pulizie · Disinfestazione",
  "hero.title1": "Sono le 23:47. Il telefono squilla.",
  "hero.title2": "Non preoccuparti.",
  "hero.sub": "Anna risponde, qualifica, preventiva e prenota — il tuo team dorme e il calendario si riempie da solo.",
  "hero.oss": "Open source · AGPL-3.0",
  "hero.star": "★ Stella su GitHub",
  "hero.selfHost": "Self-host o setup chiavi in mano",

  "story.eyebrow": "Come si vive",
  "story.title1": "Una chiamata persa,",
  "story.title2": "trasformata in lavoro prenotato.",
  "story.sub": "Una notte qualunque, come Anna la gestisce davvero.",
  "story.s1.beat": "È tardi. Il telefono squilla.",
  "story.s1.body": "23:47. Il tuo team dorme. Anche la concorrenza. Il cliente ha 30 secondi di pazienza.",
  "story.s2.beat": "Anna risponde.",
  "story.s2.body": "Saluta il cliente con la voce della tua azienda, fa le domande giuste e scopre che sono 5 finestre in salotto.",
  "story.s3.beat": "Foto. Preventivo. Confermato.",
  "story.s3.body": "Il cliente manda una foto. Anna misura dall'immagine, redige un preventivo da € 3.540 e propone un sopralluogo martedì alle 9:30 — tutto prima di andare a letto.",
  "story.s4.beat": "Ti svegli con la giornata piena.",
  "story.s4.body": "Caffè del mattino. Un sopralluogo in calendario, un preventivo inviato, un acconto in attesa. Non hai toccato il telefono.",
  "story.s4.foot": "Tutto di notte. Nessuno era sveglio.",

  "features.eyebrow": "Funzioni",
  "features.title": "Configura una volta. Cattura ogni lead.",
  "features.sub": "Imposta orari, regole di prezzo e zona. Hearthline si adatta al mestiere — dall'idraulico d'urgenza alle 2 al preventivo solare da 25.000 € a mezzogiorno.",
  "features.f1.name": "Centralino IA",
  "features.f1.body": "Mai più chiamate perse. Hearthline risponde entro due squilli, qualifica il lead in tempo reale e prenota direttamente sul calendario — con la voce che vuoi e il copione della tua azienda.",
  "features.f2.name": "Assistente chat IA",
  "features.f2.body": "Chat web, SMS e WhatsApp — la stessa Anna, la stessa memoria del cliente. Risponde in secondi, passa a un umano solo se serve.",
  "features.f3.name": "Integrazione CRM",
  "features.f3.body": "Ogni chiamata, messaggio e preventivo entra nel tuo CRM come record pulito — HubSpot, Pipedrive, Jobber, ServiceTitan o il tuo Postgres.",
  "features.f4.name": "Preventivi smart",
  "features.f4.body": "I clienti inviano una foto. Anna misura con vision, compila le voci, applica le tue regole IVA e margine, e invia un preventivo pronto per Stripe.",
  "features.f5.name": "Knowledge base IA",
  "features.f5.body": "Carica garanzia, catalogo servizi e FAQ. Anna cita le tue condizioni reali — non inventa mai un prezzo o una promessa.",
  "features.f6.name": "Analytics",
  "features.f6.body": "Dashboard in tempo reale su volume chiamate, qualità dei lead, conversione e ricavi per canale — per dimostrare che il turno notturno si ripaga.",

  "stats.eyebrow": "Perché passare",
  "stats.title": "Ogni chiamata persa è un lavoro per il concorrente.",
  "stats.body": "Hearthline risponde su ogni canale, qualifica subito e consegna al team una conversazione pronta. Anna non dorme, non fa pause e non dimentica mai la foto.",
  "stats.li1": "Chiamate ricevute mentre sei su un tetto alle 3",
  "stats.li2": "Foto trasformate in preventivi prima del caffè",
  "stats.li3": "Ogni interazione sincronizzata con HubSpot, Pipedrive o il tuo CRM",
  "stats.card1.num": "Ore 3",
  "stats.card1.label": "La perdita d'acqua che il concorrente ha perso. Anna ha risposto.",
  "stats.card2.num": "43 sec",
  "stats.card2.label": "Tempo medio dalla foto al PDF di preventivo.",
  "stats.card3.num": "€0",
  "stats.card3.label": "Per chiamata persa. Hearthline prende quelle che la mail perde.",

  "flow.eyebrow": "Il flusso",
  "flow.title": "Come un lavoro attraversa Hearthline.",
  "flow.sub": "Cinque fasi, tutte automatiche. Il cliente non sente i passaggi — ottiene risposta, preventivo e appuntamento.",

  "convo.eyebrow": "Una conversazione vera",
  "convo.title": "Anna gestisce l'obiezione, non solo il saluto.",
  "convo.sub": "Filo SMS dal vivo tra Anna e cliente. Arriva la foto, si redige il preventivo, si crea il deal, si prenota — tutto in automatico.",
  "convo.head.title": "Automazione lead in entrata",
  "convo.head.sub": "Qualifica, sincronizza il CRM, redige un preventivo — automaticamente.",
  "convo.msg1": "Devo sostituire circa 5 finestre in soggiorno. Cerco PVC bianco.",
  "convo.msg2": "Capito — 5 finestre PVC bianche. Doppio vetro standard o triplo per rumore / energia? Puoi mandare una foto veloce di una finestra dall'interno?",
  "convo.msg3": "Doppio vetro va bene. Ecco la foto.",
  "convo.msg4Pre": "Perfetto — misure ~120×140 cm dalla foto. Cinque unità, fornitura e posa: ",
  "convo.msg4Mid": " IVA inclusa. Ti ho inviato il dettaglio e un sopralluogo martedì alle 9:30. Tocca il link per confermare.",
  "convo.output": "Risultato",
  "convo.estimate": "Preventivo #E-291 · inviato",
  "convo.deal": "Deal creato · HubSpot",
  "convo.survey": "Sopralluogo · Mar 9:30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "Mestieri",
  "industries.title": "Una piattaforma. Ogni mestiere.",
  "industries.sub": "Logica prezzi, copioni e regole di dispatch già impostati per mestiere — completamente modificabili. Il tuo non c'è? Hearthline si configura per ogni flusso domestico.",
  "industries.note": "Inoltre: non in elenco? Hearthline si inserisce nel flusso che già usate. ",
  "industries.i1.name": "Termoidraulica",
  "industries.i1.body": "Routing urgenze 24/7, dispatch tecnici, contratti di manutenzione.",
  "industries.i2.name": "Serramenti",
  "industries.i2.body": "Preventivi da foto, sopralluoghi, prenotazioni di posa.",
  "industries.i3.name": "Solare & Tetti",
  "industries.i3.body": "Qualifica tetto, incentivi, coordinamento visita.",
  "industries.i4.name": "Riqualificazione energetica",
  "industries.i4.body": "Audit, bonus, flussi multi-fase.",
  "industries.i5.name": "Box & Tapparelle",
  "industries.i5.body": "Marca/modello, riparare o sostituire, chiamate fuori orario.",
  "industries.i6.name": "Elettrico",
  "industries.i6.body": "Triage urgenza vs programmato, copioni di sicurezza, upsell domotica.",
  "industries.i7.name": "Giardini & Piscine",
  "industries.i7.body": "Calendario stagionale, contratti, preventivi da foto.",
  "industries.i8.name": "Pulizie & Ripristino",
  "industries.i8.body": "Triage danni, routing assicurativo, prenotazioni ricorrenti, prima/dopo.",
  "industries.i9.name": "Disinfestazione",
  "industries.i9.body": "Triage sintomi, contratti, upsell vicinato, follow-up.",

  "config.eyebrow": "Configurabile end-to-end",
  "config.title": "La tua voce. I tuoi prezzi. Il tuo CRM. I tuoi orari.",
  "config.body": "Oltre 30 voci neurali in 7 lingue. Carica il tuo listino. Collega HubSpot, Pipedrive, Salesforce, ServiceTitan o la tua API. Orari per canale. Hearthline segue le tue regole.",
  "config.k1.l": "Voce",
  "config.k1.v": "30+ neurali · 7 lingue",
  "config.k2.l": "Prezzi",
  "config.k2.v": "Il tuo listino · per mestiere",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Orari",
  "config.k4.v": "Per canale · per giorno · festivi",
  "config.k5.l": "Clonazione voce",
  "config.k5.v": "Voce del titolare (opzionale)",
  "config.k6.l": "Self-host",
  "config.k6.v": "Codice AGPL-3.0 su GitHub (licenza commerciale disponibile)",

  "finalCta.title": "Tieni acceso il fuoco. Noi guardiamo la porta.",
  "finalCta.sub": "Anna risponde all'urgenza delle 3, alla richiamata in pausa pranzo e alla foto del cliente che non sa descrivere la perdita. Il team resta sul lavoro — l'agenda si riempie da sola.",

  "footer.tag": "L'hub di comunicazione IA 24/7 per i servizi domestici.",
  "footer.product": "Prodotto",
  "footer.resources": "Risorse",
  "footer.legal": "Legale",
  "footer.faq": "FAQ",
  "footer.privacy": "Privacy",
  "footer.terms": "Termini",
  "footer.builtBy": "Costruito da",
  "footer.bio": "Video build-along IA per dev. Assumimi per installare Hearthline.",
  "footer.copyright": "Open source sotto AGPL-3.0. Licenza commerciale disponibile.",
  "footer.bottomTail": "con cura per i team domestici.",

  "lang.label": "Lingua",
};

const pt: Dict = {
  "nav.features": "Recursos",
  "nav.how": "Como funciona",
  "nav.impact": "Impacto",
  "nav.industries": "Setores",
  "nav.docs": "Docs",
  "btn.signIn": "Entrar",
  "btn.bookDemo": "Marcar demo",
  "btn.explore": "Explorar",
  "btn.tellUs": "Conte-nos sobre o seu",
  "topbar.builtBy": "por",

  "hero.meetStrong": "Olá, sou a Anna.",
  "hero.meetTail": " Esta noite atendo o telefone — vai dormir.",
  "hero.tradesLabel": "Feito para serviços ao domicílio —",
  "hero.tradesList": "AVAC · Canalização · Telhados · Solar · Garagem · Elétrica · Jardinagem · Limpeza · Pragas",
  "hero.title1": "São 23:47. O teu telefone está a tocar.",
  "hero.title2": "Não te preocupes.",
  "hero.sub": "A Anna atende, qualifica, orça e marca — para a tua equipa dormir e o calendário encher-se sozinho.",
  "hero.oss": "Código aberto · AGPL-3.0",
  "hero.star": "★ Estrela no GitHub",
  "hero.selfHost": "Auto-hospedar ou instalação chave-na-mão",

  "story.eyebrow": "Como é, na prática",
  "story.title1": "Uma chamada perdida,",
  "story.title2": "transformada em serviço marcado.",
  "story.sub": "Vê uma noite, como a Anna a gere realmente.",
  "story.s1.beat": "É tarde. O telefone toca.",
  "story.s1.body": "23:47. A tua equipa dorme. A concorrência também. O cliente tem 30 segundos de paciência.",
  "story.s2.beat": "A Anna atende.",
  "story.s2.body": "Ela cumprimenta o cliente com a voz do teu negócio, faz as perguntas certas e descobre que são 5 janelas na sala.",
  "story.s3.beat": "Foto. Orçamento. Confirmado.",
  "story.s3.body": "O cliente envia uma foto. A Anna mede pela imagem, prepara um orçamento de 3 540 € e oferece uma visita terça às 9:30 — tudo antes de ir para a cama.",
  "story.s4.beat": "Acordas com a agenda cheia.",
  "story.s4.body": "Café da manhã. Uma visita no calendário, um orçamento enviado, um sinal à espera. Não tocaste no telefone.",
  "story.s4.foot": "Tudo durante a noite. Ninguém estava acordado.",

  "features.eyebrow": "Recursos",
  "features.title": "Configure uma vez. Capte cada lead.",
  "features.sub": "Defina horários, regras de preço e zona. Hearthline adapta-se ao seu ofício — da urgência às 2h ao orçamento solar de 25.000 € ao meio-dia.",
  "features.f1.name": "Rececionista IA por telefone",
  "features.f1.body": "Nunca perca outra chamada. Hearthline atende em dois toques, qualifica em tempo real e marca diretamente no calendário — com a voz que escolher.",
  "features.f2.name": "Assistente chat IA",
  "features.f2.body": "Chat web, SMS e WhatsApp — a mesma Anna, a mesma memória do cliente. Responde em segundos e só passa a humano quando é preciso.",
  "features.f3.name": "Integração CRM",
  "features.f3.body": "Cada chamada, mensagem e orçamento entra no teu CRM como registo limpo — HubSpot, Pipedrive, Jobber, ServiceTitan ou o teu próprio Postgres.",
  "features.f4.name": "Orçamentos inteligentes",
  "features.f4.body": "Os clientes enviam uma foto. A Anna mede com visão, compõe linhas, aplica as tuas regras de IVA e margem, e envia um orçamento pronto para Stripe.",
  "features.f5.name": "Base de conhecimento IA",
  "features.f5.body": "Carrega a tua garantia, catálogo de serviços e FAQ. A Anna cita as tuas condições reais — nunca inventa um preço ou promessa.",
  "features.f6.name": "Análise de dados",
  "features.f6.body": "Dashboards ao vivo de volume de chamadas, qualidade de leads, conversão e receita por canal — para provar que o turno da noite se paga a si próprio.",

  "stats.eyebrow": "Porquê mudar",
  "stats.title": "Cada chamada perdida é um trabalho para o concorrente.",
  "stats.body": "Hearthline atende em todos os canais, qualifica de imediato e entrega à equipa uma conversa pronta. Anna não dorme, não faz pausas e nunca esquece a foto.",
  "stats.li1": "Chamadas atendidas enquanto está num telhado às 3h",
  "stats.li2": "Fotos transformadas em orçamentos antes do café acabar",
  "stats.li3": "Cada interação sincronizada com HubSpot, Pipedrive ou o seu CRM",
  "stats.card1.num": "3h",
  "stats.card1.label": "A fuga das 3h que o concorrente perdeu. Anna atendeu.",
  "stats.card2.num": "43 s",
  "stats.card2.label": "Tempo médio entre foto e PDF do orçamento.",
  "stats.card3.num": "0 €",
  "stats.card3.label": "Por chamada perdida. Hearthline marca as que a sua caixa perde.",

  "flow.eyebrow": "O percurso",
  "flow.title": "Como um trabalho passa pelo Hearthline.",
  "flow.sub": "Cinco etapas, automatizadas. O cliente não sente as transições — recebe resposta, orçamento e horário marcado.",

  "convo.eyebrow": "Uma conversa real",
  "convo.title": "Anna trata da objeção, não só do olá.",
  "convo.sub": "Conversa SMS ao vivo entre Anna e cliente. Foto chega, orçamento redigido, deal criado, agenda marcada — tudo automático.",
  "convo.head.title": "Automação de leads recebidos",
  "convo.head.sub": "Qualifica, sincroniza o CRM, redige um orçamento — automaticamente.",
  "convo.msg1": "Preciso de substituir cerca de 5 janelas na sala. PVC branco.",
  "convo.msg2": "Entendido — 5 janelas PVC brancas. Vidro duplo padrão ou triplo para ruído / energia? Pode tirar uma foto rápida de uma janela do interior?",
  "convo.msg3": "Vidro duplo serve. Aqui está a foto.",
  "convo.msg4Pre": "Perfeito — medidas ~120×140 cm pela foto. Cinco unidades, fornecimento e instalação: ",
  "convo.msg4Mid": " com IVA. Enviei o detalhe e uma medição terça às 9:30. Toque no link para confirmar.",
  "convo.output": "Resultado",
  "convo.estimate": "Orçamento #E-291 · enviado",
  "convo.deal": "Deal criado · HubSpot",
  "convo.survey": "Medição · Ter 9:30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "Ofícios",
  "industries.title": "Uma plataforma. Todos os ofícios.",
  "industries.sub": "Lógica de preços, scripts e regras de despacho pré-ajustados por ofício — totalmente editáveis. Não vê o seu? Hearthline configura-se para qualquer fluxo doméstico.",
  "industries.note": "Além disso: não está na lista? Hearthline encaixa no fluxo que a equipa já usa. ",
  "industries.i1.name": "AVAC & Canalização",
  "industries.i1.body": "Routing urgências 24/7, despacho de técnicos, contratos de manutenção.",
  "industries.i2.name": "Janelas & Portas",
  "industries.i2.body": "Orçamentos por foto, medições, marcação de instalação.",
  "industries.i3.name": "Solar & Telhados",
  "industries.i3.body": "Qualificação de telhado, incentivos, coordenação de visitas.",
  "industries.i4.name": "Renovação energética",
  "industries.i4.body": "Auditorias, candidaturas a apoios, fluxos multi-etapa.",
  "industries.i5.name": "Garagens & Persianas",
  "industries.i5.body": "Marca/modelo, reparar vs substituir, chamadas fora de horas.",
  "industries.i6.name": "Eletricidade",
  "industries.i6.body": "Triagem urgência vs agenda, scripts de segurança, upsell domótica.",
  "industries.i7.name": "Jardins & Piscinas",
  "industries.i7.body": "Calendário sazonal, contratos, orçamentos por foto.",
  "industries.i8.name": "Limpeza & Restauro",
  "industries.i8.body": "Triagem de danos, routing seguros, marcações recorrentes, antes/depois.",
  "industries.i9.name": "Pragas",
  "industries.i9.body": "Triagem de sintomas, contratos, upsell vizinhança, follow-ups.",

  "config.eyebrow": "Configurável de ponta a ponta",
  "config.title": "A sua voz. Os seus preços. O seu CRM. O seu horário.",
  "config.body": "30+ vozes neurais em 7 idiomas. Carregue o seu tarifário. Ligue HubSpot, Pipedrive, Salesforce, ServiceTitan ou API. Horários por canal. Hearthline segue as suas regras.",
  "config.k1.l": "Voz",
  "config.k1.v": "30+ neurais · 7 idiomas",
  "config.k2.l": "Preços",
  "config.k2.v": "O seu tarifário · regras por ofício",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Horários",
  "config.k4.v": "Por canal · por dia · feriados",
  "config.k5.l": "Clonagem de voz",
  "config.k5.v": "Voz do dono (opcional)",
  "config.k6.l": "Auto-hospedado",
  "config.k6.v": "Código AGPL-3.0 no GitHub (licença comercial disponível)",

  "finalCta.title": "Mantenha o fogo aceso. Nós vigiamos a porta.",
  "finalCta.sub": "Anna atende a urgência das 3h, o retorno do almoço e a foto do cliente que não sabe descrever a fuga. A equipa fica no trabalho — a agenda enche-se sozinha.",

  "footer.tag": "O hub de comunicação IA 24/7 para serviços domésticos.",
  "footer.product": "Produto",
  "footer.resources": "Recursos",
  "footer.legal": "Legal",
  "footer.faq": "FAQ",
  "footer.privacy": "Privacidade",
  "footer.terms": "Termos",
  "footer.builtBy": "Construído por",
  "footer.bio": "Vídeos build-along IA para devs. Contrate-me para instalar Hearthline.",
  "footer.copyright": "Código aberto sob AGPL-3.0. Licença comercial disponível.",
  "footer.bottomTail": "com cuidado para equipas domésticas.",

  "lang.label": "Idioma",
};

const nl: Dict = {
  "nav.features": "Functies",
  "nav.how": "Zo werkt het",
  "nav.impact": "Impact",
  "nav.industries": "Branches",
  "nav.docs": "Docs",
  "btn.signIn": "Inloggen",
  "btn.bookDemo": "Demo plannen",
  "btn.explore": "Verkennen",
  "btn.tellUs": "Vertel ons over de jouwe",
  "topbar.builtBy": "door",

  "hero.meetStrong": "Hoi, ik ben Anna.",
  "hero.meetTail": " Ik neem vannacht de telefoon — ga slapen.",
  "hero.tradesLabel": "Gemaakt voor home services —",
  "hero.tradesList": "HVAC · Loodgieter · Dak · Zonne · Garage · Elektra · Tuin · Schoonmaak · Ongedierte",
  "hero.title1": "Het is 23:47. Je telefoon gaat.",
  "hero.title2": "Maak je geen zorgen.",
  "hero.sub": "Anna neemt op, kwalificeert, offreert en boekt — zodat je team slaapt en je agenda zichzelf vult.",
  "hero.oss": "Open source · AGPL-3.0",
  "hero.star": "★ Ster op GitHub",
  "hero.selfHost": "Self-host of kant-en-klare setup",

  "story.eyebrow": "Hoe het voelt",
  "story.title1": "Een gemiste oproep,",
  "story.title2": "wordt een geboekte klus.",
  "story.sub": "Een nacht, zoals Anna die echt afhandelt.",
  "story.s1.beat": "Het is laat. De telefoon gaat.",
  "story.s1.body": "23:47. Je team slaapt. De concurrent ook. De klant heeft 30 seconden geduld.",
  "story.s2.beat": "Anna neemt op.",
  "story.s2.body": "Ze begroet de beller met de stem van je bedrijf, stelt de juiste vragen en ontdekt dat het om 5 ramen in de woonkamer gaat.",
  "story.s3.beat": "Foto. Offerte. Bevestigd.",
  "story.s3.body": "De klant stuurt een foto. Anna meet uit het beeld, maakt een offerte van € 3.540 en biedt dinsdag 9:30 als opname-moment — allemaal voor het slapengaan.",
  "story.s4.beat": "Je wordt geboekt wakker.",
  "story.s4.body": "Ochtendkoffie. Een opname in de agenda, een offerte verstuurd, een aanbetaling in afwachting. Je hebt de telefoon niet aangeraakt.",
  "story.s4.foot": "Allemaal 's nachts. Niemand was wakker.",

  "features.eyebrow": "Functies",
  "features.title": "Eén keer instellen. Elke lead vangen.",
  "features.sub": "Bepaal openingstijden, prijsregels en werkgebied. Hearthline past zich aan jouw vak aan — van noodloodgieter om 2 uur tot een €25.000 zonneoffer 's middags.",
  "features.f1.name": "AI-telefoonreceptie",
  "features.f1.body": "Mis nooit meer een gesprek. Hearthline neemt binnen twee keer overgaan op, kwalificeert real-time en boekt direct in jouw teamagenda — met de stem en het script dat jij kiest.",
  "features.f2.name": "AI-chatassistent",
  "features.f2.body": "Webchat, sms en WhatsApp — dezelfde Anna, hetzelfde klantgeheugen. Antwoordt in seconden, schakelt alleen door naar een mens als dat moet.",
  "features.f3.name": "CRM-integratie",
  "features.f3.body": "Elk gesprek, bericht en offerte landt als nette regel in je CRM — HubSpot, Pipedrive, Jobber, ServiceTitan of je eigen Postgres.",
  "features.f4.name": "Slimme offertes",
  "features.f4.body": "Klanten sturen een foto. Anna meet met vision, stelt regels op, past btw- en margeregels toe en stuurt een Stripe-klare offerte.",
  "features.f5.name": "AI-kennisbank",
  "features.f5.body": "Upload je garantietekst, dienstencatalogus en FAQ. Anna citeert je echte voorwaarden — verzint nooit een prijs of belofte.",
  "features.f6.name": "Data-analyse",
  "features.f6.body": "Live dashboards over belvolume, leadkwaliteit, conversie en omzet per kanaal — zo bewijs je dat de nachtdienst zichzelf terugverdient.",

  "stats.eyebrow": "Waarom wisselen",
  "stats.title": "Elk gemist gesprek is een klus voor je concurrent.",
  "stats.body": "Hearthline neemt op via elk kanaal, kwalificeert direct en levert je team een verkoopklaar gesprek. Anna slaapt niet, neemt geen pauze en vergeet de foto nooit.",
  "stats.li1": "Gesprekken aangenomen terwijl jij om 3 uur op een dak staat",
  "stats.li2": "Foto's omgezet in offertes voor je koffie op is",
  "stats.li3": "Elke interactie gesynct met HubSpot, Pipedrive of je CRM",
  "stats.card1.num": "3 uur",
  "stats.card1.label": "De gesprongen leiding die je concurrent miste. Anna nam op.",
  "stats.card2.num": "43 sec",
  "stats.card2.label": "Gemiddelde tijd van klantfoto tot PDF-offerte.",
  "stats.card3.num": "€0",
  "stats.card3.label": "Per gemist gesprek. Hearthline boekt wat je inbox kwijtraakt.",

  "flow.eyebrow": "Het verloop",
  "flow.title": "Hoe een klus door Hearthline stroomt.",
  "flow.sub": "Vijf fases, volledig geautomatiseerd. De klant merkt de overdracht niet — alleen snelle reactie, offerte en geplande slot.",

  "convo.eyebrow": "Een echt gesprek",
  "convo.title": "Anna pakt het bezwaar aan, niet alleen de hallo.",
  "convo.sub": "Live SMS-draad tussen Anna en klant. Foto komt binnen, offerte gemaakt, deal aangemaakt, afspraak ingepland — alles automatisch.",
  "convo.head.title": "Automatisering inkomende leads",
  "convo.head.sub": "Kwalificeert, synct CRM, maakt offerte — automatisch.",
  "convo.msg1": "Ik moet ongeveer 5 ramen in mijn woonkamer vervangen. Wit PVC.",
  "convo.msg2": "Begrepen — 5 PVC-ramen, wit. Standaard dubbel glas of triple voor geluid / energie? Kun je een snelle foto van één raam vanaf binnen sturen?",
  "convo.msg3": "Dubbel glas is prima. Hier de foto.",
  "convo.msg4Pre": "Perfect — gemeten ~120×140 cm op de foto. Vijf stuks, levering en montage: ",
  "convo.msg4Mid": " incl. btw. Ik heb de specificatie en een inmeetafspraak dinsdag 9:30 ge-sms't. Tik op de link om te bevestigen.",
  "convo.output": "Resultaat",
  "convo.estimate": "Offerte #E-291 · verstuurd",
  "convo.deal": "Deal aangemaakt · HubSpot",
  "convo.survey": "Inmeten · Di 9:30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "Vakgebieden",
  "industries.title": "Eén platform. Elk vak.",
  "industries.sub": "Prijslogica, scripts en planningsregels per vak voor-ingesteld — volledig aanpasbaar. Niet jouw vak? Hearthline past op elke huisvlijt-flow.",
  "industries.note": "Plus: niet in de lijst? Hearthline sluit aan op de flow die je team al gebruikt. ",
  "industries.i1.name": "Loodgieter & CV",
  "industries.i1.body": "24/7 nood-routing, monteurplanning, onderhoudscontracten.",
  "industries.i2.name": "Kozijnen & Deuren",
  "industries.i2.body": "Foto-offertes, inmeten, montageafspraken.",
  "industries.i3.name": "Zon & Daken",
  "industries.i3.body": "Dakkwalificatie, subsidies, schouw-coördinatie.",
  "industries.i4.name": "Energierenovatie",
  "industries.i4.body": "Isolatie-audits, subsidieaanvragen, meerstapsflows.",
  "industries.i5.name": "Garage & Rolluiken",
  "industries.i5.body": "Merk/model, repareren of vervangen, na-uren-gesprekken.",
  "industries.i6.name": "Elektra",
  "industries.i6.body": "Nood vs gepland triage, veiligheidsscripts, smart-home upsell.",
  "industries.i7.name": "Tuin & Zwembad",
  "industries.i7.body": "Seizoensplanning, abonnementen, foto-offertes.",
  "industries.i8.name": "Schoonmaak & Herstel",
  "industries.i8.body": "Schade-triage, verzekeraarsroute, herhaalboeking, voor/na-foto's.",
  "industries.i9.name": "Ongediertebestrijding",
  "industries.i9.body": "Symptoom-triage, contracten, buurt-upsell, opvolging.",

  "config.eyebrow": "End-to-end configureerbaar",
  "config.title": "Jouw stem. Jouw prijzen. Jouw CRM. Jouw uren.",
  "config.body": "30+ neurale stemmen in 7 talen. Upload je tarievenboek. Koppel HubSpot, Pipedrive, Salesforce, ServiceTitan of je API. Tijden per kanaal. Hearthline volgt jouw regels.",
  "config.k1.l": "Stem",
  "config.k1.v": "30+ neuraal · 7 talen",
  "config.k2.l": "Prijzen",
  "config.k2.v": "Jouw tarieven · per vak",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "Uren",
  "config.k4.v": "Per kanaal · per dag · feestdagen",
  "config.k5.l": "Stem klonen",
  "config.k5.v": "Stem van eigenaar (optioneel)",
  "config.k6.l": "Self-host",
  "config.k6.v": "AGPL-3.0-code op GitHub (commerciële licentie beschikbaar)",

  "finalCta.title": "Hou het vuur aan. Wij bewaken de deur.",
  "finalCta.sub": "Anna pakt de 3-uur-noodmelding, het lunchpauze-terugbelverzoek en de foto van de klant die het lek niet kan beschrijven. Jouw team blijft aan het werk — de agenda vult zichzelf.",

  "footer.tag": "De 24/7 AI-communicatiehub voor klusbedrijven.",
  "footer.product": "Product",
  "footer.resources": "Bronnen",
  "footer.legal": "Juridisch",
  "footer.faq": "FAQ",
  "footer.privacy": "Privacy",
  "footer.terms": "Voorwaarden",
  "footer.builtBy": "Gemaakt door",
  "footer.bio": "AI build-along video's voor devs. Huur me in om Hearthline op te zetten.",
  "footer.copyright": "Open source onder AGPL-3.0. Commerciële licentie beschikbaar.",
  "footer.bottomTail": "met zorg voor klusteams.",

  "lang.label": "Taal",
};

const zh: Dict = {
  "nav.features": "功能",
  "nav.how": "工作原理",
  "nav.impact": "影响",
  "nav.industries": "行业",
  "nav.docs": "文档",
  "btn.signIn": "登录",
  "btn.bookDemo": "预约演示",
  "btn.explore": "了解更多",
  "btn.tellUs": "告诉我们你的情况",
  "topbar.builtBy": "由",

  "hero.meetStrong": "你好,我是 Anna。",
  "hero.meetTail": " 今晚我接电话 — 你去睡吧。",
  "hero.tradesLabel": "为家庭服务而生 —",
  "hero.tradesList": "暖通 · 水管 · 屋顶 · 太阳能 · 车库 · 电气 · 园林 · 保洁 · 灭虫",
  "hero.title1": "晚上 11:47,你的电话响了。",
  "hero.title2": "别担心。",
  "hero.sub": "Anna 接听、筛选、报价、预约 —— 让你的团队安睡,让日程自动填满。",
  "hero.oss": "开源 · AGPL-3.0",
  "hero.star": "★ 在 GitHub 上 Star",
  "hero.selfHost": "自部署或全包安装",

  "story.eyebrow": "实际感受",
  "story.title1": "一通错过的电话,",
  "story.title2": "变成一笔已预约的生意。",
  "story.sub": "看 Anna 真正如何处理一个夜晚。",
  "story.s1.beat": "夜深了,电话响起。",
  "story.s1.body": "11:47。你的团队睡了,对手也睡了。客户只有 30 秒的耐心。",
  "story.s2.beat": "Anna 接通。",
  "story.s2.body": "她以你公司的声音问候来电者,问出关键问题,得知客厅需要换 5 扇窗。",
  "story.s3.beat": "照片。报价。确认。",
  "story.s3.body": "客户发来照片。Anna 从图中测量,生成 $3,540 的报价,并提供周二上午 9:30 的勘测时段 —— 全在他睡前完成。",
  "story.s4.beat": "你醒来时已被预约。",
  "story.s4.body": "清晨咖啡。日程里有一次勘测,报价已发,定金正等。你没碰过电话。",
  "story.s4.foot": "全程在夜里。无人醒着。",

  "features.eyebrow": "功能",
  "features.title": "一次配置,捕获每一条线索。",
  "features.sub": "设置营业时间、定价规则和服务范围。Hearthline 适配每个行业 — 从凌晨 2 点的紧急水管到中午的 25,000 美元太阳能报价。",
  "features.f1.name": "AI 电话接待员",
  "features.f1.body": "永不漏接。Hearthline 在两声铃响内接听,实时筛选客户,直接预约到团队日历 — 用你选择的语音和你的话术。",
  "features.f2.name": "AI 聊天助手",
  "features.f2.body": "网页聊天、短信和 WhatsApp —— 同一个 Anna,同一份客户记忆。秒回应,只在必要时转给真人。",
  "features.f3.name": "CRM 集成",
  "features.f3.body": "每通电话、每条消息、每份报价都干净地进入 CRM —— HubSpot、Pipedrive、Jobber、ServiceTitan 或你自己的 Postgres。",
  "features.f4.name": "智能报价",
  "features.f4.body": "客户发来照片。Anna 用视觉测量、生成行项目、套用税率和利润规则,发出可对接 Stripe 的报价。",
  "features.f5.name": "AI 知识库",
  "features.f5.body": "上传保修条款、服务目录和常见问题。Anna 引用你真实的条件 —— 绝不编造价格或承诺。",
  "features.f6.name": "数据分析",
  "features.f6.body": "实时仪表盘,按渠道展示话务量、线索质量、转化率和收入 —— 让你证明夜班自己赚回成本。",

  "stats.eyebrow": "为什么团队选择我们",
  "stats.title": "每一个漏接的电话,都是竞争对手的订单。",
  "stats.body": "Hearthline 在每个渠道接听,即时筛选,把成熟对话交给你的团队。Anna 不睡觉、不休息,也不会忘了让客户拍照。",
  "stats.li1": "凌晨 3 点你在屋顶时,电话照样有人接",
  "stats.li2": "咖啡还没喝完,照片就变成报价单",
  "stats.li3": "所有交互同步到 HubSpot、Pipedrive 或你的 CRM",
  "stats.card1.num": "凌晨 3 点",
  "stats.card1.label": "上周二同行漏掉的爆水管电话。Anna 接到了。",
  "stats.card2.num": "43 秒",
  "stats.card2.label": "从客户照片到生成 PDF 报价的平均时长。",
  "stats.card3.num": "$0",
  "stats.card3.label": "每个漏接电话。Hearthline 替你接到。",

  "flow.eyebrow": "流程",
  "flow.title": "一个工单如何在 Hearthline 中流转。",
  "flow.sub": "五个阶段,全自动。客户感觉不到交接 — 只感觉到快速响应、报价和预约时段。",

  "convo.eyebrow": "一段真实对话",
  "convo.title": "Anna 处理异议,不止打招呼。",
  "convo.sub": "Anna 与客户的实时短信对话。照片到、报价生成、商机创建、日程预约 — 全自动。",
  "convo.head.title": "进线线索自动化",
  "convo.head.sub": "筛选线索、同步 CRM、起草报价 — 自动完成。",
  "convo.msg1": "我客厅大概要换 5 扇窗户。想要白色 PVC。",
  "convo.msg2": "明白了 — 5 扇白色 PVC 窗。标准双层玻璃,还是三层(隔音/节能)?能从屋内拍一张窗户的快照吗?",
  "convo.msg3": "双层就行。这是照片。",
  "convo.msg4Pre": "非常好 — 从照片量出大约 120×140 cm。五扇,供货并安装:",
  "convo.msg4Mid": " 含税。我已发送明细以及周二上午 9:30 的勘测时段。点击链接确认。",
  "convo.output": "输出结果",
  "convo.estimate": "报价 #E-291 · 已发送",
  "convo.deal": "商机已创建 · HubSpot",
  "convo.survey": "勘测已预约 · 周二 9:30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "行业",
  "industries.title": "一个平台,覆盖所有行业。",
  "industries.sub": "定价逻辑、话术和派单规则按行业预设,完全可编辑。没有你的行业?Hearthline 可适配任何家庭服务流程。",
  "industries.note": "另外:不在列表里?Hearthline 可对接你团队现有的任何流程。",
  "industries.i1.name": "暖通与水管",
  "industries.i1.body": "24/7 紧急路由、技师派单、维护合同。",
  "industries.i2.name": "门窗",
  "industries.i2.body": "拍照报价、量尺预约、安装预订。",
  "industries.i3.name": "太阳能与屋顶",
  "industries.i3.body": "屋顶资格判定、补贴匹配、勘测协调。",
  "industries.i4.name": "节能改造",
  "industries.i4.body": "保温评估、补贴申请、多步改造流程。",
  "industries.i5.name": "车库与卷帘门",
  "industries.i5.body": "品牌型号识别、修还是换、非工作时间来电。",
  "industries.i6.name": "电气",
  "industries.i6.body": "紧急/计划分流、安全话术、智能家居加销。",
  "industries.i7.name": "园艺与泳池",
  "industries.i7.body": "季节性排程、长期合同、拍照估价。",
  "industries.i8.name": "清洁与修复",
  "industries.i8.body": "损害分流、保险路由、循环预约、前后对比照片。",
  "industries.i9.name": "虫害控制",
  "industries.i9.body": "症状分流、合同、邻居加销、回访。",

  "config.eyebrow": "全链路可配置",
  "config.title": "你的语音。你的定价。你的 CRM。你的工时。",
  "config.body": "30+ 神经语音、7 种语言。导入你的价目表。接入 HubSpot、Pipedrive、Salesforce、ServiceTitan 或自定义 API。按渠道设置营业时间。Hearthline 听你的。",
  "config.k1.l": "语音",
  "config.k1.v": "30+ 神经语音 · 7 种语言",
  "config.k2.l": "定价",
  "config.k2.v": "你的价目 · 按行业",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "工时",
  "config.k4.v": "按渠道 · 按日 · 节假日",
  "config.k5.l": "语音克隆",
  "config.k5.v": "用老板的声音(可选)",
  "config.k6.l": "自部署",
  "config.k6.v": "GitHub 上的 AGPL-3.0 代码(提供商业许可)",

  "finalCta.title": "守住你的炉火。我们替你守门。",
  "finalCta.sub": "Anna 接凌晨 3 点的紧急来电,接午休时段的回拨,接那个说不清漏水位置的客户照片。你的团队继续干活 — 日程自己填满。",

  "footer.tag": "面向家庭服务团队的 24/7 AI 通信中心。",
  "footer.product": "产品",
  "footer.resources": "资源",
  "footer.legal": "法律",
  "footer.faq": "常见问题",
  "footer.privacy": "隐私",
  "footer.terms": "条款",
  "footer.builtBy": "构建者",
  "footer.bio": "面向开发者的 AI 实战视频。雇我为你部署 Hearthline。",
  "footer.copyright": "AGPL-3.0 开源(提供商业许可)。",
  "footer.bottomTail": "用心打造,献给家庭服务团队。",

  "lang.label": "语言",
};

const ja: Dict = {
  "nav.features": "機能",
  "nav.how": "仕組み",
  "nav.impact": "効果",
  "nav.industries": "業種",
  "nav.docs": "ドキュメント",
  "btn.signIn": "ログイン",
  "btn.bookDemo": "デモを予約",
  "btn.explore": "詳しく見る",
  "btn.tellUs": "お聞かせください",
  "topbar.builtBy": "提供:",

  "hero.meetStrong": "こんにちは、Annaです。",
  "hero.meetTail": " 今夜は私が電話に出ます — もう寝てください。",
  "hero.tradesLabel": "ホームサービスのために —",
  "hero.tradesList": "空調 · 配管 · 屋根 · 太陽光 · ガレージ · 電気 · 造園 · 清掃 · 害虫",
  "hero.title1": "夜11時47分。電話が鳴っています。",
  "hero.title2": "心配しないで。",
  "hero.sub": "Anna が応対・ヒアリング・見積・予約 — チームは眠り、カレンダーは自動で埋まります。",
  "hero.oss": "オープンソース · AGPL-3.0",
  "hero.star": "★ GitHubでスター",
  "hero.selfHost": "セルフホストまたは導入代行",

  "story.eyebrow": "リアルな夜",
  "story.title1": "一本の取り逃した電話が、",
  "story.title2": "予約済みの仕事に変わる。",
  "story.sub": "Anna が実際にこなす一晩を、追ってみましょう。",
  "story.s1.beat": "夜遅く、電話が鳴る。",
  "story.s1.body": "23:47。あなたのチームは眠っている。競合も同じ。お客様の我慢は30秒。",
  "story.s2.beat": "Anna が出る。",
  "story.s2.body": "御社の声で挨拶し、必要なヒアリングを行い、リビングの窓5枚の交換だと聞き出します。",
  "story.s3.beat": "写真。見積。確定。",
  "story.s3.body": "お客様が写真を送る。Anna が画像から採寸し、$3,540 の見積を作成、火曜9:30の現地調査を提案 — お客様が寝る前に完了。",
  "story.s4.beat": "目覚めると予約済み。",
  "story.s4.body": "朝のコーヒー。カレンダーに調査1件、見積1件送信済、頭金1件待機。あなたは電話に触れていません。",
  "story.s4.foot": "全て夜の間に。誰も起きていなかった。",

  "features.eyebrow": "機能",
  "features.title": "一度の設定で、すべてのリードを獲得。",
  "features.sub": "営業時間、料金ルール、サービス範囲を設定。Hearthlineは業種に合わせて適応します — 深夜2時の緊急配管から、昼の2万5千ドルの太陽光見積まで。",
  "features.f1.name": "AI電話受付",
  "features.f1.body": "もう着信を逃さない。Hearthlineは2コール以内に応答し、リアルタイムで見込みを判定、チームのカレンダーに直接予約します — お選びの声と、御社の応対スクリプトで。",
  "features.f2.name": "AIチャット",
  "features.f2.body": "Web チャット、SMS、WhatsApp — 同じ Anna、同じ顧客記憶。秒で返信し、必要な時だけ人に引き継ぎます。",
  "features.f3.name": "CRM連携",
  "features.f3.body": "通話・メッセージ・見積はクリーンな1件として CRM に取り込み — HubSpot、Pipedrive、Jobber、ServiceTitan、または自社 Postgres。",
  "features.f4.name": "スマート見積",
  "features.f4.body": "お客様が写真を送ると、Anna がビジョンで採寸、明細を起こし、税率と利益のルールを適用、Stripe 対応の見積を送信します。",
  "features.f5.name": "AIナレッジベース",
  "features.f5.body": "保証書、サービスカタログ、FAQ をアップロード。Anna は実際の条件のみを伝え — 価格や約束を捏造しません。",
  "features.f6.name": "データ分析",
  "features.f6.body": "通話量・リード品質・成約率・チャネル別売上のライブダッシュボード — 夜勤が自走で稼ぐことを示せます。",

  "stats.eyebrow": "なぜ切り替えるのか",
  "stats.title": "見逃した1本の電話は、競合に取られた1件の仕事。",
  "stats.body": "Hearthlineはあらゆるチャネルで応答し、即座に判定し、商談化したやり取りをチームに引き継ぎます。Annaは眠らず、休まず、写真の依頼も忘れません。",
  "stats.li1": "深夜3時に屋根の上にいても、電話には応答済み",
  "stats.li2": "コーヒーが冷める前に、写真が見積に変わる",
  "stats.li3": "すべてのやり取りをHubSpot、Pipedrive、御社CRMに同期",
  "stats.card1.num": "深夜3時",
  "stats.card1.label": "競合が逃した先週火曜の水道破裂の電話。Annaが受けました。",
  "stats.card2.num": "43秒",
  "stats.card2.label": "顧客の写真からPDF見積生成までの平均時間。",
  "stats.card3.num": "0円",
  "stats.card3.label": "見逃し電話あたり。Hearthlineが受信トレイで失う案件を獲得します。",

  "flow.eyebrow": "全体の流れ",
  "flow.title": "Hearthlineを通る案件の流れ。",
  "flow.sub": "5段階、すべて自動。顧客は引き継ぎを感じません — 素早い回答、見積、予約された枠だけが届きます。",

  "convo.eyebrow": "実際の会話",
  "convo.title": "Annaは挨拶だけでなく、反論にも対応。",
  "convo.sub": "Annaと顧客のSMSスレッドの実例。写真到着、見積作成、案件作成、予約 — すべて自動。",
  "convo.head.title": "受信リード自動化",
  "convo.head.sub": "リードを判定し、CRMへ同期、見積を起案 — 自動で。",
  "convo.msg1": "リビングの窓を5枚交換したい。白の樹脂サッシで。",
  "convo.msg2": "承知しました — 白の樹脂サッシ5枚ですね。標準のペアガラス、それとも防音/断熱でトリプルにしますか?室内から1枚、写真をお送りいただけますか?",
  "convo.msg3": "ペアで構いません。写真送ります。",
  "convo.msg4Pre": "ありがとうございます — 写真から約120×140cmと計測。5枚、供給と取付け:",
  "convo.msg4Mid": " 税込。内訳と火曜9:30の現地調査枠をSMS送信しました。リンクをタップして確定してください。",
  "convo.output": "結果",
  "convo.estimate": "見積 #E-291 · 送信済",
  "convo.deal": "案件作成 · HubSpot",
  "convo.survey": "現調予約 · 火 9:30",
  "convo.signed": "— Anna",

  "industries.eyebrow": "業種",
  "industries.title": "1つのプラットフォームで、すべての業種を。",
  "industries.sub": "料金ロジック、応対スクリプト、配車ルールは業種ごとに事前調整済み — 完全に編集可能。お探しの業種が無くても、Hearthlineはどんなホームサービスのフローにも対応します。",
  "industries.note": "さらに:リストに無くても、Hearthlineは既存のフローに組み込めます。",
  "industries.i1.name": "空調・水道",
  "industries.i1.body": "24/7緊急ルーティング、技術者派遣、保守契約。",
  "industries.i2.name": "窓・ドア",
  "industries.i2.body": "写真見積、採寸予約、施工予約。",
  "industries.i3.name": "太陽光・屋根",
  "industries.i3.body": "屋根適合判定、補助金マッチング、現地調査調整。",
  "industries.i4.name": "省エネ改修",
  "industries.i4.body": "断熱診断、補助金申請、多段階リフォーム。",
  "industries.i5.name": "ガレージ・シャッター",
  "industries.i5.body": "ブランド/型番識別、修理か交換か、時間外対応。",
  "industries.i6.name": "電気",
  "industries.i6.body": "緊急/計画の振り分け、安全スクリプト、スマートホーム提案。",
  "industries.i7.name": "造園・プール",
  "industries.i7.body": "季節スケジュール、定期契約、写真見積。",
  "industries.i8.name": "清掃・復旧",
  "industries.i8.body": "被害トリアージ、保険対応、定期予約、ビフォーアフター写真。",
  "industries.i9.name": "害虫駆除",
  "industries.i9.body": "症状トリアージ、契約、近隣提案、フォローアップ。",

  "config.eyebrow": "エンドツーエンドで設定可能",
  "config.title": "あなたの声。あなたの料金。あなたのCRM。あなたの営業時間。",
  "config.body": "30種以上のニューラル音声、7言語対応。料金表をアップロード。HubSpot、Pipedrive、Salesforce、ServiceTitan、独自APIに接続。チャネルごとに営業時間を設定。Hearthlineはあなたのルールに従います。",
  "config.k1.l": "音声",
  "config.k1.v": "30+ ニューラル · 7言語",
  "config.k2.l": "料金",
  "config.k2.v": "御社の料金表 · 業種別ルール",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "営業時間",
  "config.k4.v": "チャネル別 · 日別 · 祝日",
  "config.k5.l": "音声クローン",
  "config.k5.v": "オーナーの声を使用(任意)",
  "config.k6.l": "セルフホスト",
  "config.k6.v": "GitHubのAGPL-3.0コード(商用ライセンスあり)",

  "finalCta.title": "炉火は灯したまま。ドアは私たちが見張ります。",
  "finalCta.sub": "Annaは深夜3時の緊急、昼休みの折り返し、漏水を言葉にできない顧客の写真を受けます。チームは現場に集中 — スケジュールは自然に埋まります。",

  "footer.tag": "ホームサービス向け24/7 AIコミュニケーションハブ。",
  "footer.product": "製品",
  "footer.resources": "リソース",
  "footer.legal": "法的事項",
  "footer.faq": "FAQ",
  "footer.privacy": "プライバシー",
  "footer.terms": "利用規約",
  "footer.builtBy": "制作:",
  "footer.bio": "開発者向けのAIビルドアロング動画。Hearthline導入のご依頼歓迎。",
  "footer.copyright": "AGPL-3.0によるオープンソース(商用ライセンスあり)。",
  "footer.bottomTail": "ホームサービスチームへの想いを込めて。",

  "lang.label": "言語",
};

const ar: Dict = {
  "nav.features": "الميزات",
  "nav.how": "كيف يعمل",
  "nav.impact": "الأثر",
  "nav.industries": "القطاعات",
  "nav.docs": "الوثائق",
  "btn.signIn": "تسجيل الدخول",
  "btn.bookDemo": "احجز عرضاً توضيحياً",
  "btn.explore": "استكشف",
  "btn.tellUs": "حدّثنا عن مجالك",
  "topbar.builtBy": "بواسطة",

  "hero.meetStrong": "مرحباً، أنا آنّا.",
  "hero.meetTail": " أنا على الهاتف الليلة — اخلد إلى النوم.",
  "hero.tradesLabel": "صُمّم لخدمات المنازل —",
  "hero.tradesList": "تكييف · سباكة · أسطح · طاقة شمسية · جراج · كهرباء · حدائق · تنظيف · مكافحة آفات",
  "hero.title1": "الساعة 11:47 مساءً. هاتفك يرنّ.",
  "hero.title2": "لا تقلق.",
  "hero.sub": "Anna ترد، وتؤهّل، وتسعّر، وتحجز — ينام فريقك ويمتلئ تقويمك تلقائياً.",
  "hero.oss": "مفتوح المصدر · AGPL-3.0",
  "hero.star": "★ نجّمنا على GitHub",
  "hero.selfHost": "استضف بنفسك أو إعداد جاهز",

  "story.eyebrow": "كيف تبدو الليلة",
  "story.title1": "مكالمة فائتة،",
  "story.title2": "تتحوّل إلى مهمة محجوزة.",
  "story.sub": "تنقّل عبر ليلة واحدة، كما تديرها Anna فعلاً.",
  "story.s1.beat": "الوقت متأخر. الهاتف يرنّ.",
  "story.s1.body": "11:47 مساءً. فريقك نائم، والمنافس كذلك. العميل صبره 30 ثانية.",
  "story.s2.beat": "Anna تردّ.",
  "story.s2.body": "تحيّي المتصل بصوت شركتك، تطرح الأسئلة المناسبة، وتعرف أن الأمر يخص 5 نوافذ في غرفة المعيشة.",
  "story.s3.beat": "صورة. تسعيرة. تأكيد.",
  "story.s3.body": "يرسل العميل صورة. تقيس Anna من الصورة، وتُعدّ عرضاً بقيمة 3,540$، وتقترح موعداً يوم الثلاثاء 9:30 صباحاً — كله قبل أن ينام.",
  "story.s4.beat": "تستيقظ ولديك حجوزات.",
  "story.s4.body": "قهوة الصباح. زيارة على التقويم، عرض أُرسل، عربون ينتظر. لم تلمس الهاتف.",
  "story.s4.foot": "كل ذلك في الليل. لم يكن أحد مستيقظاً.",

  "features.eyebrow": "الميزات",
  "features.title": "اضبطها مرة. والتقط كل عميل محتمل.",
  "features.sub": "حدّد ساعات العمل، قواعد التسعير، ومنطقة الخدمة. يتكيف Hearthline مع مهنتك — من سباكة طارئة في الثانية فجراً إلى عرض طاقة شمسية بـ 25 ألف دولار ظهراً.",
  "features.f1.name": "موظف استقبال هاتفي بالذكاء الاصطناعي",
  "features.f1.body": "لا تفوّت أي اتصال. يرد Hearthline خلال رنّتين، يُقيّم العميل لحظياً، ويحجز الموعد مباشرة في تقويم فريقك — بصوتٍ تختاره وبسيناريو شركتك.",
  "features.f2.name": "مساعد دردشة ذكي",
  "features.f2.body": "دردشة الويب وSMS وWhatsApp — نفس Anna ونفس ذاكرة العميل. ترد في ثوانٍ، ولا تُحوِّل لإنسان إلا عند الحاجة.",
  "features.f3.name": "تكامل CRM",
  "features.f3.body": "كل مكالمة ورسالة وعرض يدخل CRM كسجلٍ نظيف — HubSpot أو Pipedrive أو Jobber أو ServiceTitan أو Postgres الخاص بك.",
  "features.f4.name": "عروض أسعار ذكية",
  "features.f4.body": "يرسل العملاء صورة. تقيس Anna بالرؤية، وتُعدّ البنود، وتطبّق قواعد ضريبتك وهامشك، وترسل عرضاً جاهزاً لـ Stripe.",
  "features.f5.name": "قاعدة معرفة ذكية",
  "features.f5.body": "حمّل ضمانك وكتالوج خدماتك والأسئلة الشائعة. تستشهد Anna بشروطك الحقيقية — لا تخترع سعراً ولا وعداً.",
  "features.f6.name": "تحليلات",
  "features.f6.body": "لوحات حية لحجم المكالمات وجودة العملاء المحتملين والتحويل والإيرادات لكل قناة — لتثبت أن الوردية الليلية تُسدّد تكلفتها بنفسها.",

  "stats.eyebrow": "لماذا يتحول الفريق",
  "stats.title": "كل اتصال فائت هو وظيفة يحجزها منافسك.",
  "stats.body": "يرد Hearthline على كل قناة، يُقيّم فوراً، ويسلّم فريقك محادثة جاهزة للإغلاق. آنّا لا تنام، ولا تأخذ استراحة، ولا تنسى طلب الصورة.",
  "stats.li1": "اتصالات يُردّ عليها وأنت على السطح في الثالثة فجراً",
  "stats.li2": "صور تتحول إلى عروض قبل أن تنتهي قهوتك",
  "stats.li3": "كل تفاعل مزامن مع HubSpot أو Pipedrive أو CRM لديك",
  "stats.card1.num": "3 فجراً",
  "stats.card1.label": "اتصال أنبوب منفجر فاته منافسك. آنّا ردت.",
  "stats.card2.num": "43 ثانية",
  "stats.card2.label": "المتوسط من صورة العميل إلى ملف PDF للعرض.",
  "stats.card3.num": "0$",
  "stats.card3.label": "لكل اتصال فائت. Hearthline يحجز ما يفقده بريدك.",

  "flow.eyebrow": "كيف يسير",
  "flow.title": "كيف يمر العمل عبر Hearthline.",
  "flow.sub": "خمس مراحل آلية بالكامل. لا يشعر العميل بالانتقالات — فقط ردّ سريع، عرض، وموعد محجوز.",

  "convo.eyebrow": "محادثة حقيقية",
  "convo.title": "آنّا تتعامل مع الاعتراض، لا مجرد التحية.",
  "convo.sub": "خيط رسائل مباشر بين آنّا وعميل. تصل الصورة، يُكتب العرض، يُنشأ الصفقة، يُحجز الموعد — كله آلياً.",
  "convo.head.title": "أتمتة العملاء الواردين",
  "convo.head.sub": "تُقيّم، تُزامن CRM، وتكتب عرضاً — آلياً.",
  "convo.msg1": "أحتاج لاستبدال نحو 5 نوافذ في صالتي. أبحث عن PVC أبيض.",
  "convo.msg2": "تمام — 5 نوافذ PVC بيضاء. زجاج مزدوج عادي، أم ثلاثي للعزل / الصوت؟ هل يمكنك إرسال صورة سريعة لإحدى النوافذ من الداخل؟",
  "convo.msg3": "المزدوج يكفي. هذه الصورة.",
  "convo.msg4Pre": "ممتاز — قست من الصورة ~120×140 سم. خمس وحدات، توريد وتركيب: ",
  "convo.msg4Mid": " شامل الضريبة. أرسلت لك التفاصيل وموعد معاينة الثلاثاء 9:30 صباحاً. اضغط الرابط للتأكيد.",
  "convo.output": "النتيجة",
  "convo.estimate": "العرض #E-291 · أُرسل",
  "convo.deal": "صفقة أُنشئت · HubSpot",
  "convo.survey": "معاينة محجوزة · ثلاثاء 9:30",
  "convo.signed": "— آنّا",

  "industries.eyebrow": "المهن",
  "industries.title": "منصة واحدة لكل المهن.",
  "industries.sub": "منطق التسعير والسيناريوهات وقواعد التوزيع معدّة مسبقاً لكل مهنة — وقابلة للتعديل بالكامل. مهنتك ليست هنا؟ يتكيف Hearthline مع أي تدفق لخدمات المنازل.",
  "industries.note": "وأيضاً: غير مدرج؟ يندمج Hearthline مع التدفق الذي يستخدمه فريقك. ",
  "industries.i1.name": "تكييف وسباكة",
  "industries.i1.body": "توجيه طوارئ 24/7، إيفاد فنيين، عقود صيانة.",
  "industries.i2.name": "نوافذ وأبواب",
  "industries.i2.body": "عروض أسعار بالصور، مواعيد قياس، حجز التركيب.",
  "industries.i3.name": "طاقة شمسية وأسطح",
  "industries.i3.body": "تأهيل السقف، مطابقة الحوافز، تنسيق المعاينة.",
  "industries.i4.name": "تجديد طاقي",
  "industries.i4.body": "تدقيق العزل، طلبات الدعم، تدفقات متعددة المراحل.",
  "industries.i5.name": "كراجات ودرفلات",
  "industries.i5.body": "تحديد الماركة والموديل، إصلاح أم استبدال، اتصالات خارج الدوام.",
  "industries.i6.name": "كهرباء",
  "industries.i6.body": "فرز طارئ مقابل مجدول، نصوص أمان، بيع إضافي للمنزل الذكي.",
  "industries.i7.name": "حدائق ومسابح",
  "industries.i7.body": "جدولة موسمية، عقود متكررة، تسعيرة بالصور.",
  "industries.i8.name": "تنظيف وترميم",
  "industries.i8.body": "فرز الأضرار، توجيه التأمين، حجوزات متكررة، صور قبل/بعد.",
  "industries.i9.name": "مكافحة الحشرات",
  "industries.i9.body": "فرز الأعراض، عقود، بيع إضافي للجيران، متابعة.",

  "config.eyebrow": "قابل للتهيئة من البداية للنهاية",
  "config.title": "صوتك. أسعارك. CRM لديك. ساعاتك.",
  "config.body": "أكثر من 30 صوتاً عصبياً بسبع لغات. ارفع كتاب أسعارك. اربط HubSpot وPipedrive وSalesforce وServiceTitan أو واجهتك. ساعات لكل قناة. يعمل Hearthline بقواعدك.",
  "config.k1.l": "الصوت",
  "config.k1.v": "30+ عصبي · 7 لغات",
  "config.k2.l": "التسعير",
  "config.k2.v": "كتاب أسعارك · حسب المهنة",
  "config.k3.l": "CRM",
  "config.k3.v": "HubSpot · Pipedrive · Salesforce · API",
  "config.k4.l": "الساعات",
  "config.k4.v": "حسب القناة · حسب اليوم · العطلات",
  "config.k5.l": "استنساخ الصوت",
  "config.k5.v": "صوت المالك (اختياري)",
  "config.k6.l": "استضافة ذاتية",
  "config.k6.v": "كود AGPL-3.0 على GitHub (ترخيص تجاري متاح)",

  "finalCta.title": "أبقِ النار مشتعلة. نحن نراقب الباب.",
  "finalCta.sub": "آنّا ترد على طوارئ الثالثة فجراً، ومعاودة الاتصال بعد الغداء، وصورة العميل الذي لا يستطيع وصف التسرب. فريقك يكمل عمله — والجدول يمتلئ وحده.",

  "footer.tag": "مركز التواصل الذكي 24/7 لفرق خدمات المنازل.",
  "footer.product": "المنتج",
  "footer.resources": "الموارد",
  "footer.legal": "قانوني",
  "footer.faq": "الأسئلة الشائعة",
  "footer.privacy": "الخصوصية",
  "footer.terms": "الشروط",
  "footer.builtBy": "بُني بواسطة",
  "footer.bio": "فيديوهات بناء عملية بالذكاء الاصطناعي للمطورين. وظّفني لتنصيب Hearthline.",
  "footer.copyright": "مفتوح المصدر تحت AGPL-3.0. ترخيص تجاري متاح.",
  "footer.bottomTail": "بعناية لفرق خدمات المنازل.",

  "lang.label": "اللغة",
};

export const DICTS: Record<Lang, Dict> = { en, es, de, fr, it, pt, nl, zh, ja, ar };

export function tFor(lang: Lang, key: string): string {
  const dict = DICTS[lang] || en;
  return dict[key] ?? en[key] ?? key;
}
